### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by relaxart** [hoangdangal/lazadatest#3]
Migrations contain information only about users. 
How to get rest of the tables?

**Comment by hoangdangal** [comment]
Users is default table of Laravel framework,Because I supplied sql dump file so I did not create migration information.I will update if you need.

**Comment by rmribeiro** [comment]
We do need @hoangdangal! Thanks

**Comment by hoangdangal** [comment]
hi I have updated database migration , please check , thanks
